### ISSUE TITLE
Cannot run the app gives PageNotFound

### ISSUE THREAD

**Issue by she12** [hendisantika/spring-mvc-email#1]
Steps to create the project:
1. cloned the project from git,
2. In STS, import as Existing Maven projects,
3. Run as Spring boot 
4. Accessing it at localhost:/8080, gives page cannot be found.

Log messages from console:
xxx HomeController.showHomePage GET
2018-01-03 12:32:24.941  WARN 19101 --- [nio-8080-exec-1] o.s.web.servlet.PageNotFound             : No mapping found for HTTP request with URI [/WEB-INF/views/home.jsp] in DispatcherServlet with name 'dispatcherServlet'

The first line is system out added in HomeController to see if the flow reaches the controller.
Why is it giving PageNotFound

**Comment by hendisantika** [comment]
Sorry, I just realize there was an issue here.

I will fix it soon, @she12.

**Comment by hendisantika** [comment]
The issue has been resolved @she12 .
I will push & merge it tomorrow ya.
Wait for my new bug fix.

**Comment by hendisantika** [comment]
OK @she12.

I already fixed the code.
Please pull again from the beginning and read the README.md file.

Please enjoy it.

Let me know if You any error.
